# Exercises: Data cleaning and preprocessing

In this notebook, you will read in data from multiple sources. You will merge these datasets based on a specific column, which you will standardize between datasources. You will clean and preprocess this data so it can be used for analytics or machine learning.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Assignment description

You are provided with two datasets. The first is a dataset on [World Happiness Indices and Corruption from 2015 to 2020](https://www.kaggle.com/datasets/eliasturk/world-happiness-based-on-cpi-20152020), and the second contains the [All-time Olympic Games medal counts per country from 1896 to 2022](https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table). The goal of this assignment is to produce a dataset that can be used to investigate whether there is a relationship between happiness indices and medals won in the Olympic Games. In order to do so, you will need to do the following:
1. Standardize the country names across both datasets.
2. Convert categorical columns to numerical.
3. Remove or impute missing data.
4. Merge the datasets into one DataFrame.

## 1 Load and explore the datasets

Run the following codecell to load the datasets.

**Exercise 1: Use pandas to check the contents of the datasets. What do you see?**

Check the sources of the datasets using the hyperlinks provided. What should the DataFrames look like? What should the names of the columns be?

In [2]:
happiness_df = pd.read_csv('WorldHappiness_Corruption_2015_2020.csv')
olympics_df = pd.read_csv('olympics.csv')

In [4]:
# YOUR CODE HERE

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 792 entries, 0 to 791
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Country            792 non-null    object
 1   happiness_score    792 non-null    float64
 2   gdp_per_capita     792 non-null    float64
 3   family             792 non-null    float64
 4   health             792 non-null    float64
 5   freedom            792 non-null    float64
 6   generosity         792 non-null    float64
 7   government_trust   792 non-null    float64
 8   dystopia_residual  792 non-null    float64
 9   continent          792 non-null    object
 10  Year               792 non-null    int64
 11  social_support     792 non-null    float64
 12  cpi_score          792 non-null    int64
dtypes: float64(9), int64(2), object(2)
memory usage: 80.6+ KB

## 2 Data cleaning

### 2.1 Cleaning the World Happiness Report dataset

**Exercise 2:**

Use pandas to do the following:
1. Convert the "continent" column from a categorical column to numeric "dummy" columns.
2. Replace all values of 0.0 with np.nan. This is because missing values have been entered as 0.0 in this dataset.
3. The dataset contains values for the years 2015 to 2020. Group each country by the average of its values across the years, then drop the "Year" column. Hint: use the pandas .groupby() method for this.

When you are done, the final DataFrame should look something like the preview below.

In [ ]:
# YOUR CODE HERE

,Country,happiness_score,gdp_per_capita,family,health,freedom,generosity,government_trust,dystopia_residual,social_support,cpi_score,continent_Africa,continent_Asia,continent_Australia,continent_Europe,continent_North America,continent_South America
0,Afghanistan,3.355150,0.347712,0.165794,0.256598,0.098270,0.245648,0.048616,1.292619,0.235072,15.333333,0.0,1.0,0.0,0.0,0.0,0.0
1,Albania,4.740950,0.933303,0.351609,0.797468,0.386906,0.168410,0.040228,1.159740,0.415914,36.666667,0.0,0.0,0.0,1.0,0.0,0.0
2,Algeria,5.557183,1.001445,0.509505,0.678451,0.162688,0.077502,0.143281,1.708258,0.576167,34.833333,1.0,0.0,0.0,0.0,0.0,0.0
3,Argentina,6.378617,1.097274,0.625800,0.775708,0.488157,0.088660,0.063659,1.775399,0.712091,39.000000,0.0,0.0,0.0,0.0,0.0,1.0
4,Armenia,4.440467,0.833988,0.401561,0.710852,0.243037,0.086532,0.049742,1.121172,0.513263,38.166667,0.0,1.0,0.0,0.0,0.0,0.0

### 2.2 Cleaning the Olympics dataset

**Exercise 3:**

Use pandas to do the following:
1. Skip one row and set the header as the first (0-indexed) row
2. Rename the columns with sensible names. Use the source of the dataset to help you with this.
3. Remove the columns for the Summer and Winter games, and only keep the columns for the total games and total medals.
4. Rename the countries in the first column so that they do not have the country codes (the initials in parantheses). Hint: look up Python string methods and RegEx (regular expressions) to help you do this.
5. Create a new column "Medals per game", where you divide the total medals won by the total games.

When you are done, the final DataFrame should look something like the preview below.

In [ ]:
# YOUR CODE HERE

,Country,# Games,Gold total,Silver total,Bronze total,Combined total,Medals per game
0,Afghanistan,13,0,0,2,2,0.153846
1,Algeria,15,5,2,8,15,1.000000
2,Argentina,41,18,24,28,70,1.707317
3,Armenia,11,1,2,9,12,1.090909
4,Australasia,2,3,4,5,12,6.000000

## 3 Merging datasets

### 3.1 Merging the World Happiness dataset with the Olympics dataset

**Exercise 4:**

Use pandas to merge the two DataFrames into one, based on the "Country" column. Keep only the countries where we have data from both sources, and discard the unmatched data, i.e. perform an "inner" join. Hint: use pandas.DataFrame.merge() for this.

How many countries do we have in our merged dataset?

In [ ]:
# YOUR CODE HERE

## 4 EDA

**Exercise 5:**

Use Matplotlib and/or Seaborn to do the following:
1. Visualize the relationship between the happiness score and the total Olympic medals won per country.
2. Visualize the relationship between the happiness score and the Olympic medals won per games participated per country.
3. Plot a graph showing the number of gold, silver and bronze medals won per continent.
4. Is there a relationship between GDP per capita and the total number of Olympic medals won?

Feel free to make other visualizations and graphs to explore this dataset even more.

In [ ]:
# YOUR CODE HERE